# Generated by Django 3.1.3 on 2021-12-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20211220_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='choices',
        ),
        migrations.CreateModel(
            name='Submission_choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='onlinecourse.Choice')),
                ('submission', models.ManyToManyField(to='onlinecourse.Submission')),
            ],
        ),
    ]
